import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const companies = [
  { cif: "B08123456", name: "TechBcn Solutions S.L.", legalForm: "S.L.", foundedYear: 2015, address: "Carrer de Balmes 120", postalCode: "08008", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 45, revenue: 3200000, phone: "934567890", email: "info@techbcn.es", website: "techbcn.es", linkedinUrl: "linkedin.com/company/techbcn", techStack: '["React","Node.js","AWS"]', description: "Desarrollo de software a medida para pymes" },
  { cif: "B28654321", name: "Madrid Digital Hub S.L.", legalForm: "S.L.", foundedYear: 2018, address: "Gran Vía 45", postalCode: "28013", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6311", cnaeDescription: "Proceso de datos, hosting", employees: 28, revenue: 1800000, phone: "915678901", email: "hola@madridhub.es", website: "madridhub.es", techStack: '["Azure","Python","Django"]', description: "Hosting y servicios cloud" },
  { cif: "B46789012", name: "ValenciaWeb Studio S.L.", legalForm: "S.L.", foundedYear: 2020, address: "Avinguda del Port 88", postalCode: "46023", city: "Valencia", provincia: "Valencia", ccaa: "Comunidad Valenciana", cnaeCode: "6312", cnaeDescription: "Portales web", employees: 12, revenue: 800000, phone: "963456789", email: "contacto@vlcweb.es", website: "vlcweb.es", techStack: '["WordPress","PHP","WooCommerce"]', description: "Diseño web y ecommerce" },
  { cif: "B08234567", name: "Automatiza BCN S.L.", legalForm: "S.L.", foundedYear: 2021, address: "Carrer d'Aragó 255", postalCode: "08007", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6202", cnaeDescription: "Consultoría informática", employees: 8, revenue: 450000, phone: "932345678", email: "info@automatizabcn.com", website: "automatizabcn.com", techStack: '["n8n","Make","Zapier","Python"]', description: "Automatización de procesos para pymes" },
  { cif: "B28345678", name: "CyberShield España S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Paseo de la Castellana 200", postalCode: "28046", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6209", cnaeDescription: "Otros servicios TI", employees: 65, revenue: 5500000, phone: "917890123", email: "info@cybershield.es", website: "cybershield.es", techStack: '["Splunk","CrowdStrike","AWS"]', description: "Ciberseguridad gestionada" },
  { cif: "B08345678", name: "DataFlow Analytics S.L.", legalForm: "S.L.", foundedYear: 2017, address: "Carrer de Provença 339", postalCode: "08037", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6311", cnaeDescription: "Proceso de datos, hosting", employees: 32, revenue: 2800000, phone: "931234567", email: "hello@dataflow.es", website: "dataflow.es", techStack: '["Snowflake","dbt","Tableau","Python"]', description: "BI y análisis de datos" },
  { cif: "B46890123", name: "AppVLC Factory S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Carrer de Colón 60", postalCode: "46004", city: "Valencia", provincia: "Valencia", ccaa: "Comunidad Valenciana", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 18, revenue: 1200000, phone: "961234567", email: "info@appvlc.com", website: "appvlc.com", techStack: '["Flutter","Firebase","React Native"]', description: "Desarrollo de apps móviles" },
  { cif: "B28456789", name: "CloudFirst Madrid S.L.", legalForm: "S.L.", foundedYear: 2016, address: "Calle de Serrano 90", postalCode: "28006", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6311", cnaeDescription: "Proceso de datos, hosting", employees: 55, revenue: 4200000, phone: "918901234", email: "info@cloudfirst.es", website: "cloudfirst.es", techStack: '["AWS","Terraform","Kubernetes","Docker"]', description: "Migración cloud y DevOps" },
  { cif: "B08456789", name: "FinTech Soluciones S.L.", legalForm: "S.L.", foundedYear: 2020, address: "Passeig de Gràcia 78", postalCode: "08008", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6619", cnaeDescription: "Actividades auxiliares financieras", employees: 40, revenue: 3500000, phone: "933456789", email: "info@fintechsoluciones.es", website: "fintechsoluciones.es", techStack: '["Java","Spring Boot","PostgreSQL"]', description: "Software para sector financiero" },
  { cif: "B41567890", name: "Andalucía IT Services S.L.", legalForm: "S.L.", foundedYear: 2014, address: "Avenida de la Constitución 20", postalCode: "41004", city: "Sevilla", provincia: "Sevilla", ccaa: "Andalucía", cnaeCode: "6202", cnaeDescription: "Consultoría informática", employees: 22, revenue: 1500000, phone: "954567890", email: "info@andaluciait.es", website: "andaluciait.es", techStack: '["SAP","Oracle",".NET"]', description: "Consultoría IT y ERP" },
  { cif: "B48678901", name: "Biscay Digital S.L.", legalForm: "S.L.", foundedYear: 2018, address: "Gran Vía 50", postalCode: "48011", city: "Bilbao", provincia: "Bizkaia", ccaa: "País Vasco", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 15, revenue: 1100000, phone: "944567890", email: "info@biscaydigital.eus", website: "biscaydigital.eus", techStack: '["Vue.js","Laravel","MySQL"]', description: "Desarrollo web y transformación digital" },
  { cif: "B29789012", name: "Costa Sol Tech S.L.", legalForm: "S.L.", foundedYear: 2021, address: "Calle Larios 15", postalCode: "29005", city: "Málaga", provincia: "Málaga", ccaa: "Andalucía", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 10, revenue: 600000, phone: "952345678", email: "info@costasoltech.es", website: "costasoltech.es", techStack: '["Next.js","Vercel","Supabase"]', description: "Startup fullstack" },
  { cif: "B50890123", name: "Aragón Automate S.L.", legalForm: "S.L.", foundedYear: 2022, address: "Paseo Independencia 30", postalCode: "50004", city: "Zaragoza", provincia: "Zaragoza", ccaa: "Aragón", cnaeCode: "6202", cnaeDescription: "Consultoría informática", employees: 6, revenue: 320000, phone: "976345678", email: "info@aragonautomate.es", website: "aragonautomate.es", techStack: '["Power Automate","SharePoint","Azure"]', description: "Automatización con Microsoft 365" },
  { cif: "B08567890", name: "HealthTech BCN S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Avinguda Diagonal 440", postalCode: "08037", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 35, revenue: 2500000, phone: "934561234", email: "info@healthtechbcn.com", website: "healthtechbcn.com", techStack: '["React","Python","FastAPI","PostgreSQL"]', description: "Software para sector sanitario" },
  { cif: "B28567890", name: "LegalTech Pro S.L.", legalForm: "S.L.", foundedYear: 2020, address: "Calle de Alcalá 120", postalCode: "28009", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 20, revenue: 1800000, phone: "916789012", email: "info@legaltechpro.es", website: "legaltechpro.es", techStack: '["Angular","Node.js","MongoDB"]', description: "Soluciones para despachos de abogados" },
  { cif: "B08678901", name: "EcoSmart Solutions S.L.", legalForm: "S.L.", foundedYear: 2021, address: "Carrer de Mallorca 200", postalCode: "08036", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "7112", cnaeDescription: "Ingeniería y consultoría técnica", employees: 14, revenue: 900000, phone: "935671234", email: "info@ecosmart.es", website: "ecosmart.es", techStack: '["IoT","Python","InfluxDB","Grafana"]', description: "IoT y monitorización energética" },
  { cif: "B46901234", name: "Logística Digital VLC S.L.", legalForm: "S.L.", foundedYear: 2017, address: "Carrer de la Reina 50", postalCode: "46011", city: "Valencia", provincia: "Valencia", ccaa: "Comunidad Valenciana", cnaeCode: "5229", cnaeDescription: "Otras actividades de transporte", employees: 50, revenue: 4000000, phone: "962345678", email: "info@logisticadigital.es", website: "logisticadigital.es", techStack: '["SAP","React","PostgreSQL"]', description: "Digitalización de cadena de suministro" },
  { cif: "B28678901", name: "EdTech Innova S.L.", legalForm: "S.L.", foundedYear: 2018, address: "Calle de Goya 55", postalCode: "28001", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "8559", cnaeDescription: "Otra educación", employees: 25, revenue: 1600000, phone: "914567890", email: "info@edtechinnova.es", website: "edtechinnova.es", techStack: '["React","Django","AWS","WebRTC"]', description: "Plataformas e-learning" },
  { cif: "B08789012", name: "Retail Analytics S.L.", legalForm: "S.L.", foundedYear: 2016, address: "Rambla de Catalunya 80", postalCode: "08008", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "7320", cnaeDescription: "Estudios de mercado", employees: 30, revenue: 2200000, phone: "936781234", email: "info@retailanalytics.es", website: "retailanalytics.es", techStack: '["Python","Spark","Looker","BigQuery"]', description: "Análisis predictivo para retail" },
  { cif: "B41678901", name: "GreenTech Sevilla S.L.", legalForm: "S.L.", foundedYear: 2022, address: "Calle Sierpes 40", postalCode: "41004", city: "Sevilla", provincia: "Sevilla", ccaa: "Andalucía", cnaeCode: "3511", cnaeDescription: "Producción de energía eléctrica", employees: 8, revenue: 500000, phone: "955678901", email: "info@greentechsevilla.es", website: "greentechsevilla.es", techStack: '["IoT","MQTT","Node-RED","InfluxDB"]', description: "Monitorización de plantas solares" },
  { cif: "B08890123", name: "Chatbot Factory S.L.", legalForm: "S.L.", foundedYear: 2023, address: "Carrer de Pau Claris 100", postalCode: "08009", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 7, revenue: 280000, phone: "937891234", email: "info@chatbotfactory.es", website: "chatbotfactory.es", techStack: '["OpenAI","LangChain","FastAPI","Pinecone"]', description: "Chatbots e IA conversacional" },
  { cif: "B28789012", name: "PropTech Madrid S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Paseo del Prado 18", postalCode: "28014", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6831", cnaeDescription: "Agentes inmobiliarios", employees: 16, revenue: 1300000, phone: "915891234", email: "info@proptechmadrid.es", website: "proptechmadrid.es", techStack: '["React","Rails","PostgreSQL","Mapbox"]', description: "Tecnología para sector inmobiliario" },
  { cif: "B46012345", name: "AgroTech Levante S.L.", legalForm: "S.L.", foundedYear: 2020, address: "Carrer de Xàtiva 25", postalCode: "46002", city: "Valencia", provincia: "Valencia", ccaa: "Comunidad Valenciana", cnaeCode: "0161", cnaeDescription: "Actividades de apoyo agricultura", employees: 11, revenue: 700000, phone: "964567890", email: "info@agrotechlevante.es", website: "agrotechlevante.es", techStack: '["IoT","LoRaWAN","Python","PostgreSQL"]', description: "Agricultura de precisión" },
  { cif: "B08901234", name: "HRTech People S.L.", legalForm: "S.L.", foundedYear: 2018, address: "Via Augusta 200", postalCode: "08021", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "6202", cnaeDescription: "Consultoría informática", employees: 22, revenue: 1700000, phone: "938901234", email: "info@hrtechpeople.com", website: "hrtechpeople.com", techStack: '["React","Node.js","MongoDB","Stripe"]', description: "Software de RRHH" },
  { cif: "B28890123", name: "InsurTech Solutions S.L.", legalForm: "S.L.", foundedYear: 2021, address: "Calle de Velázquez 70", postalCode: "28001", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6512", cnaeDescription: "Seguros distintos de vida", employees: 18, revenue: 1400000, phone: "916901234", email: "info@insurtechsol.es", website: "insurtechsol.es", techStack: '["Java","Angular","Oracle","Docker"]', description: "Plataformas digitales para aseguradoras" },
  { cif: "B48789012", name: "Indus4 Euskadi S.L.", legalForm: "S.L.", foundedYear: 2017, address: "Alameda de Recalde 27", postalCode: "48009", city: "Bilbao", provincia: "Bizkaia", ccaa: "País Vasco", cnaeCode: "7112", cnaeDescription: "Ingeniería y consultoría técnica", employees: 40, revenue: 3800000, phone: "945678901", email: "info@indus4.eus", website: "indus4.eus", techStack: '["Siemens MindSphere","Python","OPC-UA","Grafana"]', description: "Industria 4.0 y gemelos digitales" },
  { cif: "B08012345", name: "MarTech Barcelona S.L.", legalForm: "S.L.", foundedYear: 2020, address: "Carrer del Comte d'Urgell 150", postalCode: "08036", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "7311", cnaeDescription: "Agencias de publicidad", employees: 15, revenue: 1100000, phone: "939012345", email: "info@martechbcn.com", website: "martechbcn.com", techStack: '["HubSpot","Google Ads API","Python","BigQuery"]', description: "Marketing automation" },
  { cif: "B29890123", name: "TechPark Málaga S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Calle Marie Curie 10, PTA", postalCode: "29590", city: "Málaga", provincia: "Málaga", ccaa: "Andalucía", cnaeCode: "6201", cnaeDescription: "Programación informática", employees: 25, revenue: 2000000, phone: "953456789", email: "info@techparkmalaga.es", website: "techparkmalaga.es", techStack: '["Rust","Go","Kubernetes","GCP"]', description: "Desarrollo backend de alto rendimiento" },
  { cif: "B08123789", name: "Supply Chain AI S.L.", legalForm: "S.L.", foundedYear: 2022, address: "Carrer de la Marina 16", postalCode: "08005", city: "Barcelona", provincia: "Barcelona", ccaa: "Cataluña", cnaeCode: "5229", cnaeDescription: "Otras actividades de transporte", employees: 12, revenue: 650000, phone: "930123456", email: "info@supplychainai.es", website: "supplychainai.es", techStack: '["Python","TensorFlow","FastAPI","Redis"]', description: "IA para optimización logística" },
  { cif: "B28901234", name: "GovTech España S.L.", legalForm: "S.L.", foundedYear: 2019, address: "Calle de Atocha 80", postalCode: "28012", city: "Madrid", provincia: "Madrid", ccaa: "Comunidad de Madrid", cnaeCode: "6202", cnaeDescription: "Consultoría informática", employees: 35, revenue: 3000000, phone: "917012345", email: "info@govtechespana.es", website: "govtechespana.es", techStack: '["Java","Angular","PostgreSQL","Docker"]', description: "Digitalización de administraciones públicas" },
];

async function main() {
  console.log("Seeding OBX Leads...");
  const hashedPassword = await bcrypt.hash("demo1234", 10);
  const user = await prisma.user.upsert({
    where: { email: "demo@obxleads.com" },
    update: {},
    create: { email: "demo@obxleads.com", name: "Demo User", hashedPassword, plan: "growth" },
  });
  for (const c of companies) {
    await prisma.company.upsert({ where: { cif: c.cif }, update: {}, create: c });
  }
  const list = await prisma.list.create({ data: { name: "Pymes Tech Barcelona", userId: user.id } });
  const bcnCompanies = await prisma.company.findMany({ where: { provincia: "Barcelona" }, take: 5 });
  for (const c of bcnCompanies) {
    await prisma.listCompany.create({ data: { listId: list.id, companyId: c.id } });
  }
  console.log(`Seeded: ${companies.length} companies, 1 user (demo@obxleads.com / demo1234), 1 list`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
